/* tslint:disable */
export const fileNames = {
	'angular-cli.json': '_file_angular',
	'bower.json': '_file_bower',
	license: '_file_license',
	LICENSE: '_file_license',
	'license.txt': '_file_license',
	'license.md': '_file_license',
	dockerfile: '_file_docker',
	'docker-compose': '_file_docker',
	'docker-compose.ci-build': '_file_docker',
	'docker-compose.override': '_file_docker',
	'docker-compose.vs.debug': '_file_docker',
	'docker-compose.vs.release': '_file_docker',
	'docker-cloud': '_file_docker',
	emakefile: '_file_erlang',
	'go.sum': '_file_go',
	'go.mod': '_file_go',
	'gruntfile.js': '_file_grunt',
	'gruntfile.coffee': '_file_grunt',
	'gruntfile.ts': '_file_grunt',
	'gruntfile.babel.js': '_file_grunt',
	'gruntfile.babel.coffee': '_file_grunt',
	'gruntfile.babel.ts': '_file_grunt',
	'gulpfile.js': '_file_gulp',
	'gulpfile.coffee': '_file_gulp',
	'gulpfile.ts': '_file_gulp',
	'gulpfile.babel.js': '_file_gulp',
	'gulpfile.babel.coffee': '_file_gulp',
	'gulpfile.babel.ts': '_file_gulp',
	'package.json': '_file_npm',
	'package-lock.json': '_file_package-lock',
	'yarn.lock': '_file_yarn-lock',
	'yarn-error.log': '_file_yarn',
	makefile: '_file_settings',
	'postcss.config.js': '_file_postcss',
	'postcss.config.ts': '_file_postcss',
	CODEOWNERS: '_file_github',
	'tsconfig.json': '_file_json',
	'tslint.json': '_file_json',
	'composer.lock': '_file_json',
	'stylelint.config.js': '_file_stylelint',
	'stylelint.config.ts': '_file_stylelint',
	'stylelint.config.json': '_file_stylelint',
	'stylelint.config.yml': '_file_stylelint',
	'stylelint.config.yaml': '_file_stylelint',
	'ionic.config.json': '_file_ionic',
	'.io-config.json': '_file_ionic',
	'babelrc.js': '_file_babel',
	'babelrc.json': '_file_babel',
	'babel.config.js': '_file_babel',
	'webpack.base.conf.js': '_file_webpack',
	'webpack.base.conf.ts': '_file_webpack',
	'webpack.common.js': '_file_webpack',
	'webpack.common.ts': '_file_webpack',
	'webpack.config.js': '_file_webpack',
	'webpack.config.ts': '_file_webpack',
	'webpack.config.base.js': '_file_webpack',
	'webpack.config.base.ts': '_file_webpack',
	'webpack.config.common.js': '_file_webpack',
	'webpack.config.common.ts': '_file_webpack',
	'webpack.config.dev.js': '_file_webpack',
	'webpack.config.dev.ts': '_file_webpack',
	'webpack.config.development.js': '_file_webpack',
	'webpack.config.development.ts': '_file_webpack',
	'webpack.config.staging.js': '_file_webpack',
	'webpack.config.staging.ts': '_file_webpack',
	'webpack.config.test.js': '_file_webpack',
	'webpack.config.test.ts': '_file_webpack',
	'webpack.config.prod.js': '_file_webpack',
	'webpack.config.prod.ts': '_file_webpack',
	'webpack.config.production.js': '_file_webpack',
	'webpack.config.production.ts': '_file_webpack',
	'webpack.config.babel.js': '_file_webpack',
	'webpack.config.babel.ts': '_file_webpack',
	'webpack.config.base.babel.js': '_file_webpack',
	'webpack.config.base.babel.ts': '_file_webpack',
	'webpack.config.common.babel.js': '_file_webpack',
	'webpack.config.common.babel.ts': '_file_webpack',
	'webpack.config.dev.babel.js': '_file_webpack',
	'webpack.config.dev.babel.ts': '_file_webpack',
	'webpack.config.development.babel.js': '_file_webpack',
	'webpack.config.development.babel.ts': '_file_webpack',
	'webpack.config.staging.babel.js': '_file_webpack',
	'webpack.config.staging.babel.ts': '_file_webpack',
	'webpack.config.test.babel.js': '_file_webpack',
	'webpack.config.test.babel.ts': '_file_webpack',
	'webpack.config.prod.babel.js': '_file_webpack',
	'webpack.config.prod.babel.ts': '_file_webpack',
	'webpack.config.production.babel.js': '_file_webpack',
	'webpack.config.production.babel.ts': '_file_webpack',
	'webpack.dev.js': '_file_webpack',
	'webpack.dev.ts': '_file_webpack',
	'webpack.dev.conf.js': '_file_webpack',
	'webpack.dev.conf.ts': '_file_webpack',
	'webpack.prod.js': '_file_webpack',
	'webpack.prod.ts': '_file_webpack',
	'webpack.prod.conf.js': '_file_webpack',
	'webpack.prod.conf.ts': '_file_webpack',
	'webpack.mix.js': '_file_webpack',
	'webpack.mix.ts': '_file_webpack',
	'webpack.test.conf.js': '_file_webpack',
	'webpack.test.conf.ts': '_file_webpack',
	'rollup.config.js': '_file_rollup',
	'rollup-config.ts': 'file_rollup',
	'rollup.config.common.js': 'file_rollup',
	'rollup.config.common.ts': 'file_rollup',
	'rollup.config.base.js': 'file_rollup',
	'rollup.config.base.ts': 'file_rollup',
	'rollup.config.prod.js': 'file_rollup',
	'rollup.config.prod.ts': 'file_rollup',
	'rollup.config.dev.js': 'file_rollup',
	'rollup.config.dev.ts': 'file_rollup',
	'rollup.config.prod.vendor.js': 'file_rollup',
	'rollup.config.prod.vendor.ts': 'file_rollup',
	'jest.config.js': '_file_jest',
	'jest.json': '_file_jest',
	'jest.config.json': '_file_jest',
	'jest.config.ts': '_file_jest',
	'jest.setup.js': '_file_jest',
	'jest.setup.ts': '_file_jest',
	'jest.teardown.js': '_file_jest',
	'contributing.md': '_file_contributing',
	'code_of_conduct.md': '_file_conduct',
	'gatsby-config.js': '_file_gatsby',
	'gatsby-config.ts': '_file_gatsby',
	'gatsby-node.js': '_file_gatsby',
	'gatsby-node.ts': '_file_gatsby',
	'gatsby-browser.js': '_file_gatsby',
	'gatsby-browser.ts': '_file_gatsby',
	'gatsby-ssr.js': '_file_gatsby',
	'gatsby-ssr.ts': '_file_gatsby',
	'readme.md': '_file_readme',
	'README.md': '_file_readme',
	changelog: '_file_changelog',
	'changelog.md': '_file_changelog',
	favicon: '_file_favicon',
	'prettier.config.js': '_file_prettier',
	'mix.lock': '_file_elixir-lock',
	'now.json': '_file_now',
	browserslistrc: '_file_browserlist',
	'nuxt.config.js': '_file_nuxtconfig',
	'vue.config.js': '_file_vue'
	// jenkinsfile: '_file_jenkins',
	// 'gatsby.config.js': '_file_gatsby',
	// 'firebase.json': '_file_firebase',
	// '.firebaserc': '_file_firebase',

	// 'gradle.properties': '_file_gradle',
	// gradlew: '_file_gradle',
	// 'androidmanifest.xml': '_file_android',
	// 'gradle-wrapper.properties': '_file_gradle',
	// procfile: '_file_procfile',
	// '.env': '_file_tune',
	// '.env.development': '_file_tune',
	// '.env.testing': '_file_tune',
	// '.env.staging': '_file_tune',
	// '.env.production': '_file_tune',
	// dockerfile: '_file_docker',
	// 'babel.config.js': '_file_babel',
	// '.babelrc': '_file_babel',
	// '.babelrc.js': '_file_babel',
	// '.babelrc.json': '_file_babel',
	// '.htaccess': '_file_xml',
	// '.gitignore': '_file_git',
	// '.gitconfig': '_file_git',
	// '.gitattributes': '_file_git',
	// '.gitmodules': '_file_git',
	// '.gitkeep': '_file_git',
	// 'cargo.lock': '_file_cargo-lock',
	// '.mailmap': '_file_email',
	// CREDITS: '_file_credits',
	// 'credits.txt': '_file_credits',
	// 'credits.md': '_file_credits',
	// 'credits.md.rendered': '_file_credits',
	// '.flowconfig': '_file_flow',
	// 'git-history': '_file_git',
	// 'directive.ts': '_file_angular-directive',
	// 'directive.js': '_file_angular-directive',
	// 'favicon.ico': '_file_favicon',
};
