/* tslint:disable */
export const fileExtensions = {
	ai: '_file_ai',
	applescript: '_file_applescript',
	'module.ts': '_file_angular',
	'module.js': '_file_angular',
	'module.dart': '_file_angular',
	'.angular-cli.json': '_file_angular',
	'component.ts': '_file_angular-component',
	'component.js': '_file_angular-component',
	'component.dart': '_file_angular-component',
	'directive.ts': '_file_angular-directive',
	'directive.js': '_file_angular-directive',
	'directive.dart': '_file_angular-directive',
	'guard.ts': '_file_angular-guard',
	'guard.js': '_file_angular-guard',
	'guard.dart': '_file_angular-guard',
	'service.ts': '_file_angular-service',
	'service.js': '_file_angular-service',
	'service.dart': '_file_angular-service',
	'pipe.ts': '_file_angular-pipe',
	'pipe.js': '_file_angular-pipe',
	'pipe.dart': '_file_angular-pipe',
	'filter.ts': '_file_angular-pipe',
	'filter.js': '_file_angular-pipe',
	'filter.dart': '_file_angular-pipe',
	'resolver.ts': '_file_angular-resolver',
	'resolver.js': '_file_angular-resolver',
	'resolver.dart': '_file_angular-resolver',
	'routing.ts': '_file_angular-routing',
	'routing.js': '_file_angular-routing',
	'routing.dart': '_file_angular-routing',
	cs: '_file_csharp',
	csx: '_file_csharp',
	coffee: '_file_coffee',
	css: '_file_css',
	bowerrc: '_file_bower',
	gitattributes: '_file_git',
	gitconfig: '_file_git',
	gitignore: '_file_git',
	gitmodules: '_file_git',
	gitkeep: '_file_git',
	mailmap: '_file_git',
	patch: '_file_git',
	d: '_file_dlang',
	dockerfile: '_file_docker',
	dockerignore: '_file_docker',
	erl: '_file_erlang',
	emakerfile: '_file_erlang',
	go: '_file_go',
	gv: '_file_graphviz',
	hs: '_file_haskell',
	png: '_file_image',
	jpeg: '_file_image',
	jpg: '_file_image',
	gif: '_file_image',
	webp: '_file_image',
	apng: '_file_image',
	tiff: '_file_image',
	tif: '_file_image',
	ico: '_file_image',
	java: '_file_java',
	js: '_file_js',
	mjs: '_file_js',
	'node-version': '_file_node',
	nvmrc: '_file_node',
	less: '_file_less',
	md: '_file_markdown',
	mdx: '_file_markdown',
	tmTheme: '_file_markup',
	tmcolor: '_file_markup',
	php: '_file_php',
	php1: '_file_php',
	php2: '_file_php',
	php3: '_file_php',
	php4: '_file_php',
	php5: '_file_php',
	php6: '_file_php',
	phps: '_file_php',
	phpsa: '_file_php',
	phpt: '_file_php',
	phtml: '_file_php',
	phar: '_file_php',
	psd: '_file_psd',
	py: '_file_python',
	rails: '_file_rails',
	npmignore: '_file_npm',
	npmrc: '_file_npm',
	yarnrc: '_file_yarn',
	yarnclean: '_file_yarn',
	'yarn-integrity': '_file_yarn',
	rb: '_file_ruby',
	rs: '_file_rust',
	scss: '_file_sass',
	sass: '_file_sass',
	scala: '_file_scala',
	ini: '_file_settings',
	dlc: '_file_settings',
	dll: '_file_settings',
	config: '_file_settings',
	conf: '_file_settings',
	properties: '_file_settings',
	prop: '_file_settings',
	settings: '_file_settings',
	props: '_file_settings',
	toml: '_file_settings',
	prefs: '_file_settings',
	env: '_file_settings',
	buildignore: '_file_settings',
	editorconfig: '_file_settings',
	jshintignore: '_file_settings',
	sh: '_file_console',
	ksh: '_file_console',
	csh: '_file_console',
	tcsh: '_file_console',
	zsh: '_file_console',
	awk: '_file_console',
	ps1: '_file_console',
	fish: '_file_console',
	bash: '_file_console',
	bat: '_file_console',
	cmd: '_file_console',
	slim: '_file_slim',
	sql: '_file_sql',
	sqlite: '_file_sql-lite',
	sqlite3: '_file_sql-lite',
	db3: '_file_sql-lite',
	swift: '_file_swift',
	swig: '_file_swig',
	twig: '_file_twig',
	pug: '_file_pug',
	jade: '_file_jade',
	'jade-lintrc': '_file_pug',
	'pug-lintrc': '_file_pug',
	'jade-lint.json': '_file_pug',
	'pug-lintrc.js': '_file_pug',
	'pug-lintrc.json': '_file_pug',
	ts: '_file_typescript',
	'd.ts': '_file_typescript_def',
	'spec.ts': '_file_typescript_def',
	pl: '_file_perl',
	pl6: '_file_perl',
	postcss: '_file_postcss',
	pcss: '_file_postcss',
	postcssrc: '_file_postcss',
	'postcssrc.js': '_file_postcss',
	'postcssrc.yml': '_file_postcss',
	'postcssrc.json': '_file_postcss',
	json: '_file_json',
	jsonc: '_file_json',
	jsonnet: '_file_json',
	json5: '_file_json',
	jscsrc: '_file_json',
	jshintrc: '_file_json',
	jsbeautifyrc: '_file_json',
	ml: '_file_ocaml',
	mat: '_file_matlab',
	fig: '_file_matlab',
	mex: '_file_matlab',
	mexn: '_file_matlab',
	mexrs6: '_file_matlab',
	mn: '_file_matlab',
	mum: '_file_matlab',
	mx: '_file_matlab',
	mx3: '_file_matlab',
	rwd: '_file_matlab',
	slx: '_file_matlab',
	slddc: '_file_matlab',
	smv: '_file_matlab',
	xvc: '_file_matlab',
	m: '_file_matlab',
	cc: '_file_cpp',
	cpp: '_file_cpp',
	'c++': '_file_cpp',
	hpp: '_file_cpp',
	hxx: '_file_cpp',
	hh: '_file_cpp',
	mm: '_file_cpp',
	cxx: '_file_cpp',
	yml: '_file_yaml',
	yaml: '_file_yaml',
	vue: '_file_vue',
	styl: '_file_stylus',
	'blade.php': '_file_blade',
	blade: '_file_blade',
	'inky.php': '_file_blade',
	svg: '_file_svg',
	eps: '_file_svg',
	zip: '_file_zip',
	rar: '_file_zip',
	'7z': '_file_zip',
	tar: '_file_zip',
	gz: '_file_zip',
	bzip2: '_file_zip',
	xz: '_file_zip',
	bz2: '_file_zip',
	re: '_file_reason',
	sketch: '_file_sketch',
	gql: '_file_graphql',
	gqlconfig: '_file_graphql',
	eslintrc: '_file_eslint',
	eslintignore: '_file_eslint',
	eslintcache: '_file_eslint',
	'eslintrc.json': '_file_eslint',
	'eslintrc.js': '_file_eslint',
	'eslintrc.yml': '_file_eslint',
	'eslintrc.yaml': '_file_eslint',
	'eslintignore.json': '_file_eslint',
	'eslintignore.js': '_file_eslint',
	'eslintignore.yml': '_file_eslint',
	'eslintignore.yaml': '_file_eslint',
	'eslintcache.json': '_file_eslint',
	'eslintcache.js': '_file_eslint',
	'eslintcache.yml': '_file_eslint',
	'eslintcache.yaml': '_file_eslint',
	stylelintrc: '_file_stylelint',
	stylelintignore: '_file_stylelint',
	stylelintcache: '_file_stylelint',
	'stylelintrc.js': '_file_stylelint',
	'stylelintrc.json': '_file_stylelint',
	'stylelintrc.yml': '_file_stylelint',
	'stylelintrc.yaml': '_file_stylelint',
	'ionic.project': '_file_ionic',
	haml: '_file_haml',
	babelrc: '_file_babel',
	'babelrc.js': '_file_babel',
	babelignore: '_file_babel',
	jestrc: '_file_jestrc',
	aac: '_file_audio',
	act: '_file_audio',
	aiff: '_file_audio',
	amr: '_file_audio',
	ape: '_file_audio',
	au: '_file_audio',
	dct: '_file_audio',
	dss: '_file_audio',
	dvf: '_file_audio',
	flac: '_file_audio',
	gsm: '_file_audio',
	iklax: '_file_audio',
	ivs: '_file_audio',
	m4a: '_file_audio',
	m4b: '_file_audio',
	m4p: '_file_audio',
	mmf: '_file_audio',
	mogg: '_file_audio',
	mp3: '_file_audio',
	mpc: '_file_audio',
	msv: '_file_audio',
	oga: '_file_audio',
	ogg: '_file_audio',
	opus: '_file_audio',
	ra: '_file_audio',
	raw: '_file_audio',
	tta: '_file_audio',
	vox: '_file_audio',
	wav: '_file_audio',
	wma: '_file_audio',
	'gitlab-ci.yml': '_file_gitlab',
	'js.flow': '_file_flow',
	flowconfig: '_file_flow',
	woff: '_file_font',
	woff2: '_file_font',
	ttf: '_file_font',
	otf: '_file_font',
	eot: '_file_font',
	pfa: '_file_font',
	pfb: '_file_font',
	sfd: '_file_font',
	suit: '_file_font',
	bmap: '_file_font',
	fnt: '_file_font',
	odttf: '_file_font',
	ttc: '_file_font',
	'story.tsx': '_file_storybook',
	'story.ts': '_file_storybook',
	'story.jsx': '_file_storybook',
	'story.js': '_file_storybook',
	'stories.tsx': '_file_storybook',
	'stories.ts': '_file_storybook',
	'stories.jsx': '_file_storybook',
	'stories.js': '_file_storybook',
	xml: '_file_xml',
	txt: '_file_document',
	liquid: '_file_liquid',
	hbs: '_file_handlebars',
	vscodeignore: '_file_visualstudio',
	vsixmanifest: '_file_visualstudio',
	suo: '_file_visualstudio',
	sln: '_file_visualstudio',
	csproj: '_file_visualstudio',
	vb: '_file_visualstudio',
	'js.map': '_file_js_map',
	'mjs.map': '_file_js_map',
	pub: '_file_key',
	key: '_file_key',
	pem: '_file_key',
	asc: '_file_key',
	svelte: '_file_svelte',
	elm: '_file_elm',
	jsx: '_file_react',
	tsx: '_file_react',
	webm: '_file_movie',
	mkv: '_file_movie',
	flv: '_file_movie',
	vob: '_file_movie',
	ogv: '_file_movie',
	gifv: '_file_movie',
	avi: '_file_movie',
	mov: '_file_movie',
	qt: '_file_movie',
	wmv: '_file_movie',
	yuv: '_file_movie',
	rm: '_file_movie',
	rmvb: '_file_movie',
	mp4: '_file_movie',
	m4v: '_file_movie',
	mpg: '_file_movie',
	mp2: '_file_movie',
	mpeg: '_file_movie',
	mpe: '_file_movie',
	mpv: '_file_movie',
	m2v: '_file_movie',
	'prettierrc.js': '_file_prettier',
	'prettierrc.json': '_file_prettier',
	'prettierrc.yaml': '_file_prettier',
	'prettierrc.yml': '_file_prettier',
	prettierrc: '_file_prettier',
	prettierignore: '_file_prettier',
	proto: '_file_protobuf',
	ex: '_file_elixir',
	tf: '_file_terraform',
	'graphqlconfig.yml': '_file_graphql',
	'graphqlconfig.yaml': '_file_graphql',
	mjml: '_file_mjml'
	// cabal: '_file_cabal',
	// cfc: '_file_coldfusion',
	// cfm: '_file_coldfusion',
	// mdx: '_file_mdx',
	// lnk: '_file_lnk',
	// pm: '_file_perl',
	// pl: '_file_perl',
	// jl: '_file_julia',
	// gv: '_file_graphviz',
	// erl: '_file_erlang',
	// hx: '_file_haxe',
	// zep: '_file_zephyr',
	// mjs: '_file_node',
	// scala: '_file_scala',
	// asp: '_file_html',
	// aspx: '_file_html',
	// ascx: '_file_html',
	// mustache: '_file_mustache',
	// rails: '_file_rails',
	// styl: '_file_stylus',
	// twig: '_file_twig',
	// swig: '_file_swig',
	// sketch: '_file_sketch',
	// do: '_file_todo',
	// todo: '_file_todo',
	// 'sublime-settings': '_file_sublime',
	// 'sublime-theme': '_file_sublime',
	// 'sublime-commands': '_file_sublime',
	// 'sublime-menu': '_file_sublime',
	// html: '_file_html',
	// lit: '_file_html',
	// jade: '_file_pug',
	// markdown: '_file_markdown',
	// 'markdown.rendered': '_file_markdown',
	// 'YAML-tmLanguage': '_file_yaml',
	// yml: '_file_yaml',
	// xml: '_file_xml',
	// plist: '_file_xml',
	// xsd: '_file_xml',
	// dtd: '_file_xml',
	// xsl: '_file_xml',
	// xslt: '_file_xml',
	// resx: '_file_xml',
	// iml: '_file_xml',
	// xquery: '_file_xml',
	// tmLanguage: '_file_xml',,
	// psd: '_file_psd',
	// psb: '_file_psd',
	// ami: '_file_image',
	// apx: '_file_image',
	// bmp: '_file_image',
	// bpg: '_file_image',
	// brk: '_file_image',
	// cur: '_file_image',
	// dds: '_file_image',
	// dng: '_file_image',
	// exr: '_file_image',
	// fpx: '_file_image',
	// gbr: '_file_image',
	// img: '_file_image',
	// jbig2: '_file_image',
	// jb2: '_file_image',
	// jng: '_file_image',
	// jxr: '_file_image',
	// pbm: '_file_image',
	// pgf: '_file_image',
	// pic: '_file_image',
	// raw: '_file_image',
	// webp: '_file_image',
	// php: '_file_php',
	// js: '_file_js',
	// ejs: '_file_html',
	// esx: '_file_js',
	// pdf: '_file_pdf',
	// xlsx: '_file_table',
	// xls: '_file_table',
	// csv: '_file_table',
	// pdb: '_file_database',
	// exe: '_file_exe',
	// msi: '_file_exe',
	// java: '_file_java',
	// jar: '_file_java',
	// jsp: '_file_java',
	// c: '_file_c',
	// h: '_file_c',
	// go: '_file_go',
	// py: '_file_python',
	// url: '_file_url',
	// gradle: '_file_gradle',
	// doc: '_file_word',
	// docx: '_file_word',
	// rtf: '_file_word',
	// sql: '_file_database',
	// db: '_file_database',
	// accdb: '_file_database',
	// mdb: '_file_database',
	// cer: '_file_certificate',
	// cert: '_file_certificate',
	// crt: '_file_certificate',
	// lib: '_file_lib',
	// rb: '_file_ruby',
	// erb: '_file_ruby',
	// lock: '_file_ruby',
	// fs: '_file_fsharp',
	// fsx: '_file_fsharp',
	// fsi: '_file_fsharp',
	// fsproj: '_file_fsharp',
	// manifest: '_file_xml',
	// swift: '_file_swift',
	// ino: '_file_arduino',
	// tex: '_file_tex',
	// cls: '_file_tex',
	// sty: '_file_tex',
	// bib: '_file_lib',
	// pptx: '_file_powerpoint',
	// ppt: '_file_powerpoint',
	// pptm: '_file_powerpoint',
	// potx: '_file_powerpoint',
	// pot: '_file_powerpoint',
	// potm: '_file_powerpoint',
	// ppsx: '_file_powerpoint',
	// ppsm: '_file_powerpoint',
	// pps: '_file_powerpoint',
	// ppam: '_file_powerpoint',
	// ppa: '_file_powerpoint',
	// vdi: '_file_virtual',
	// vbox: '_file_virtual',
	// 'vbox-prev': '_file_virtual',
	// ics: '_file_email',
	// coffee: '_file_coffee',
	// sqlite: '_file_database',
	// graphql: '_file_graphql',
	// graphqlconfig: '_file_graphql',
	// gql: '_file_graphql',

	// rs: '_file_rust',
	// raml: '_file_raml',
	// xaml: '_file_xaml',
	// hs: '_file_haskell',
	// kt: '_file_kotlin',
	// project: '_file_xml',
	// dockerfile: '_file_docker',
	// lua: '_file_lua',
	// clj: '_file_clojure',
	// groovy: '_file_groovy',
	// r: '_file_r',
	// rst: '_file_markdown',
	// dart: '_file_dart',
	// as: '_file_actionscript',
	// mxml: '_file_mxml',
	// ahk: '_file_autohotkey',
	// swf: '_file_flash',
	// swc: '_file_swc',
	// cmake: '_file_cmake',
	// asm: '_file_assembly',
	// a51: '_file_assembly',
	// inc: '_file_assembly',
	// nasm: '_file_assembly',
	// s: '_file_assembly',
	// ms: '_file_assembly',
	// agc: '_file_assembly',
	// ags: '_file_assembly',
	// aea: '_file_assembly',
	// argus: '_file_assembly',
	// mitigus: '_file_assembly',
	// binsource: '_file_assembly',
	// vue: '_file_vue',
	// ml: '_file_ocaml',
	// mli: '_file_ocaml',
	// cmx: '_file_ocaml',
	// 'css.map': '_file_cssmap',
	// pp: '_file_puppet',
	// applescript: '_file_applescript',
	// ex: '_file_ex',
	// exs: '_file_ex',
	// eex: '_file_ex',
	// re: '_file_reason',
	// rei: '_file_reason',
	// note: '_file_note',
};
