/* tslint:disable */
export const folderNames = {
	build: '_file_folder_dist',
	dist: '_file_folder_dist',
	out: '_file_folder_dist',
	src: '_file_folder_src',
	source: '_file_folder_src',
	assets: '_file_folder_assets',
	node_modules: '_file_folder_node',
	'.github': '_file_folder_github',
	'.vscode': '_file_folder_vscode',
	test: '_file_folder_test',
	tests: '_file_folder_test',
	__test__: '_file_folder_test',
	__tests__: '_file_folder_test'
	// ci: '_folder_ci',
	// bower_components: '_folder_bower',
	// js: '_folder_js',
	// css: '_folder_css',
	// style: '_folder_style',
	// sass: '_folder_sass',
	// scss: '_folder_sass',
	// images: '_folder_images',
	// '.git': '_folder_git',
	// '.gulp': '_folder_gulp',
	// gulp: '_folder_gulp',
};
