/* tslint:disable */
export const languageIds = {
	svelte: '_file_svelte',
	'ng-template': '_file_angular',
	'git-commit': '_file_git',
	'git-rebase': '_file_git',
	git: '_file_git',
	diff: '_file_git',
	gitignore: '_file_git',
	applescript: '_file_applescript',
	csharp: '_file_csharp',
	coffeescript: '_file_coffee',
	css: '_file_css',
	d: '_file_dlang',
	dscript: '_file_dlang',
	dml: '_file_dlang',
	diet: '_file_dlang',
	dockerfile: '_file_docker',
	erlang: '_file_erlang',
	go: '_file_go',
	dot: '_file_graphviz',
	haskell: '_file_haskell',
	html: '_file_html',
	java: '_file_java',
	javascript: '_file_js',
	juliamarkdown: '_file_julia',
	julia: '_file_julia',
	less: '_file_less',
	markdown: '_file_markdown',
	mdx: '_file_markdown',
	php: '_file_php',
	ruby: '_file_ruby',
	rust: '_file_rust',
	sass: '_file_sass',
	scala: '_file_scala',
	dotenv: '_file_settings',
	slim: '_file_slim',
	sql: '_file_sql',
	swift: '_file_swift',
	swig: '_file_swig',
	twig: '_file_twig',
	jade: '_file_pug',
	typescript: '_file_typescript',
	perl: '_file_perl',
	perl6: '_file_perl6',
	postcss: '_file_postcss',
	json: '_file_json',
	jsonc: '_file_json',
	'json-tmlanguage': '_file_json'
	// haxe: '_file_haxe',
	// hxml: '_file_haxe',
	// polymer: '_file_polymer',
	// matlab: '_file_matlab',
	// bat: '_file_cmd',
	// c: '_file_c',
	// csharp: '_file_csharp',
	// cpp: '_file_cpp',
	// css: '_file_css',
	// clojure: '_file_clojure',
	// coffeescript: '_file_coffee',
	// dart: '_file_dart',
	// dockerfile: '_file_docker',
	// fsharp: '_file_fsharp',
	// go: '_file_go',
	// groovy: '_file_groovy',
	// html: '_file_html',
	// handlebars: '_file_handlebars',
	// ini: '_file_settings',
	// java: '_file_java',
	// javascript: '_file_js',
	// javascriptreact: '_file_react',
	// less: '_file_less',
	// lua: '_file_lua',
	// makefile: '_file_settings',
	// markdown: '_file_markdown',
	// 'objective-c': '_file_matlab',
	// 'objective-cpp': '_file_cpp',
	// php: '_file_php',
	// perl: '_file_perl',
	// perl6: '_file_perl',
	// plaintext: '_file_document',
	// powershell: '_file_console',
	// properties: '_file_settings',
	// proto3: '_file_protobuf',
	// jade: '_file_pug',
	// python: '_file_python',
	// r: '_file_r',
	// ruby: '_file_ruby',
	// rust: '_file_rust',
	// scss: '_file_sass',
	// shellscript: '_file_console',
	// swift: '_file_swift',
	// typescript: '_file_typescript',
	// typescriptreact: '_file_react',
	// vb: '_file_visualstudio',
	// xml: '_file_xml',
	// xsl: '_file_xml',
	// yaml: '_file_yaml'
};
